version: "3.9"

name: "UASP-AKSO"

services:
  web:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./website:/usr/share/nginx/html # Sinkronisasi folder lokal dengan container
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    networks:
      - web_network

  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: exampledb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80" # Akses PGAdmin melalui http://localhost:8081
    networks:
      - postgres_network
    configs:
      - source: pgadmin_config
        target: /pgadmin_config # Lokasi konfigurasi dalam container

  redis:
    image: redis:6.2
    container_name: redis_container
    networks:
      - cache_network
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - web_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  influxdb:
    image: influxdb:2.0
    container_name: influxdb_container
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - monitoring_network
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    networks:
      - monitoring_network
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  memcached:
    image: memcached:1.6
    container_name: memcached_container
    ports:
      - "11211:11211"
    networks:
      - web_network
    volumes:
      - memcached_data:/data

networks:
  web_network:
    driver: bridge
  postgres_network:
    driver: bridge
  cache_network:
    driver: bridge
  monitoring_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  influxdb_data:
    driver: local
  grafana_data:
    driver: local
  rabbitmq_data:
    driver: local
  memcached_data:
    driver: local

configs:
  nginx_config:
    file: ./nginx.conf
  pgadmin_config:
    file: ./pgadmin-custom-config.conf
